// Generated by CoffeeScript 1.9.0
var Applet, GLib, Gettext, MyApplet, Util, main, _,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Applet = imports.ui.applet;

GLib = imports.gi.GLib;

Util = imports.misc.util;

Gettext = imports.gettext.domain('cinnamon-applets');

_ = Gettext.gettext;

MyApplet = (function() {
  var base;

  MyApplet.prototype.__proto__ = base = Applet.IconApplet.prototype;

  MyApplet.prototype.name = 'Gracie';

  function MyApplet(orientation) {
    this.on_applet_clicked = __bind(this.on_applet_clicked, this);
    var e;
    base._init.call(this, orientation);
    try {
      this.set_applet_icon_name("gnome-info");
      this.set_applet_tooltip(_("Say Hello, " + this.name));
      return;
    } catch (_error) {
      e = _error;
      global.logError(e);
      return;
    }
  }

  MyApplet.prototype.on_applet_clicked = function(evtdata) {
    var notification;
    notification = "notify-send \"Hello " + this.name + "\"  -a TEST -t 10 -u low";
    Util.spawnCommandLine(notification);
  };

  return MyApplet;

})();

main = function(metadata, orientation) {
  return new MyApplet(orientation);
};
