// Generated by CoffeeScript 1.9.0
var Applet, GLib, Gettext, Lang, MyApplet, Util, main, _;

Lang = imports.lang;

Applet = imports.ui.applet;

GLib = imports.gi.GLib;

Util = imports.misc.util;

Gettext = imports.gettext.domain('cinnamon-applets');

_ = Gettext.gettext;

MyApplet = (function() {
  MyApplet.prototype.__proto__ = Applet.IconApplet.prototype;

  function MyApplet(orientation) {
    var e;
    Applet.IconApplet.prototype._init.call(this, orientation);
    try {
      this.set_applet_icon_name("lock-computer");
      this.set_applet_tooltip(_("Click here to test computer"));
      return;
    } catch (_error) {
      e = _error;
      global.logError(e);
      return;
    }
  }

  MyApplet.prototype.on_applet_clicked = function(evtdata) {
    var notification;
    notification = "notify-send \"this is a test\"  -a TEST -t 10 -u low";
    Util.spawnCommandLine(notification);
  };

  return MyApplet;

})();

main = function(metadata, orientation) {
  var myApplet;
  myApplet = new MyApplet(orientation);
  return myApplet;
};
