js2coffee prolog.js > ../out/prolog.coffee
js2coffee VisibleChildIterator.js > ../out/VisibleChildIterator.coffee
js2coffee ApplicationContextMenuItem.js > ../out/ApplicationContextMenuItem.coffee
js2coffee AppPopupSubMenuMenuItem.js > ../out/AppPopupSubMenuMenuItem.coffee
js2coffee GenericApplicationButton.js > ../out/GenericApplicationButton.coffee
js2coffee TransientButton.js > ../out/TransientButton.coffee
js2coffee ApplicationButton.js > ../out/ApplicationButton.coffee
js2coffee PlaceButton.js > ../out/PlaceButton.coffee
js2coffee RecentButton.js > ../out/RecentButton.coffee
js2coffee RecentClearButton.js > ../out/RecentClearButton.coffee
js2coffee CategoryButton.js > ../out/CategoryButton.coffee
js2coffee PlaceCategoryButton.js > ../out/PlaceCategoryButton.coffee
js2coffee RecentCategoryButton.js > ../out/RecentCategoryButton.coffee
js2coffee FavoritesButton.js > ../out/FavoritesButton.coffee
js2coffee TextBoxItem.js > ../out/TextBoxItem.coffee
js2coffee AllProgramsItem.js > ../out/AllProgramsItem.coffee
js2coffee HoverIcon.js > ../out/HoverIcon.coffee
js2coffee ShutdownContextMenuItem.js > ../out/ShutdownContextMenuItem.coffee
js2coffee ShutdownMenu.js > ../out/ShutdownMenu.coffee
js2coffee CategoriesApplicationsBox.js > ../out/CategoriesApplicationsBox.coffee
js2coffee RightButtonsBox.js > ../out/RightButtonsBox.coffee
js2coffee FavoritesBox.js > ../out/FavoritesBox.coffee
